include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  language:
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: true
    directives_ordering: true
    require_trailing_commas: true
    use_super_parameters: true
    avoid_print: true
